version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: music_teacher_user
      POSTGRES_PASSWORD: djembelessons
      POSTGRES_DB: djembe_teacher_db
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: