"""Initial migration for PostgreSQL

Revision ID: 640a9ba44aef
Revises: 
Create Date: 2025-08-12 08:37:46.708926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '640a9ba44aef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_process',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('added_by', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('text')
    )
    with op.batch_alter_table('learning_process', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_process_timestamp'), ['timestamp'], unique=False)

    op.create_table('lesson_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_name', sa.String(length=100), nullable=False),
    sa.Column('price_duration', sa.String(), nullable=True),
    sa.Column('comment', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('added_by', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lesson_price', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lesson_price_timestamp'), ['timestamp'], unique=False)

    op.create_table('text_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('added_by', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('text')
    )
    with op.batch_alter_table('text_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_text_data_timestamp'), ['timestamp'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    with op.batch_alter_table('text_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_text_data_timestamp'))

    op.drop_table('text_data')
    with op.batch_alter_table('lesson_price', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lesson_price_timestamp'))

    op.drop_table('lesson_price')
    with op.batch_alter_table('learning_process', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_process_timestamp'))

    op.drop_table('learning_process')
    # ### end Alembic commands ###
