"""Change price_duration from Float to String

Revision ID: bd49ecdc7d6a
Revises: f45f5397e484
Create Date: 2025-05-26 15:52:31.681658

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'bd49ecdc7d6a'
down_revision = 'f45f5397e484'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson_price', schema=None) as batch_op:
        batch_op.alter_column('price_duration',
               existing_type=sa.FLOAT(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson_price', schema=None) as batch_op:
        batch_op.alter_column('price_duration',
               existing_type=sa.String(),
               type_=sa.FLOAT(),
               existing_nullable=True)

    # ### end Alembic commands ###
